# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('saved', models.BooleanField(default=1)),
                ('checked', models.BooleanField(default=0)),
                ('translated', models.BooleanField(default=0)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='examples.Template')),
            ],
        ),
    ]
