# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('saved', models.BooleanField(default=0)),
                ('checked', models.BooleanField(default=0)),
                ('translated', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='done',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatestate',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='examples.Template'),
        ),
    ]
