# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('usage', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('usage', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
