# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('usage', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sentence',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='usage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
